name: Package Health

on:
  schedule:
    # Run weekly on Wednesdays at 1 AM UTC.
    - cron: '0 1 * * 3'
  workflow_dispatch:
  push:
    paths:
      - 'package.json'
      - 'dist/**'
      - 'tsconfig.json'

permissions:
  contents: read

jobs:
  package-health:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run publint validation
        run: npm run lint:package

      - name: Check bundle size
        run: |
          npm pack --dry-run
          echo "📦 Package contents:"
          npm pack --dry-run | grep -E '\.(js|d\.ts)$' || true
          echo ""
          echo "📊 Bundle size analysis:"
          du -sh dist/
          ls -la dist/

      - name: Test package installation simulation
        run: |
          # Create a test directory and simulate global install
          mkdir test-install
          cd test-install
          npm init -y
          npm pack ../
          tar -tf *.tgz
          cd ..
          rm -rf test-install

      - name: Verify CLI executable
        run: |
          # Test that the CLI can be executed and shows help
          echo "🔧 Testing CLI help output:"
          node dist/index.js --help || echo "No --help flag available"
          echo ""
          echo "🔧 Testing CLI with sample input:"
          echo "# Test
          
          This is a [test link](https://example.com)." | node dist/index.js || echo "CLI test completed"
          
      - name: Check TypeScript types
        run: |
          # Verify TypeScript declaration files are valid
          echo "🔍 Validating TypeScript declarations:"
          npx tsc --noEmit --skipLibCheck dist/transformer.d.ts
          echo "✅ TypeScript declarations are valid"

      - name: Validate package exports
        run: |
          # Test that package exports work correctly
          echo "📤 Testing package exports:"
          node -e "
            try {
              const transformer = require('./dist/transformer.js');
              console.log('✅ Main export works:', typeof transformer);
            } catch (e) {
              console.log('❌ Main export failed:', e.message);
              process.exit(1);
            }
          "

      - name: Check package size limits
        run: |
          # Warn if package gets too large
          PACKAGE_SIZE=$(npm pack --dry-run 2>/dev/null | tail -1 | awk '{print $NF}' | sed 's/B$//')
          echo "📏 Package size: ${PACKAGE_SIZE}B"
          # Warn if over 1MB (1048576 bytes)
          if [ "$PACKAGE_SIZE" -gt 1048576 ]; then
            echo "⚠️ Warning: Package size exceeds 1MB"
          else
            echo "✅ Package size is reasonable"
          fi
